package com.gl.ceir;

public interface ProcessName {
	
	String REGISTERED_DEVICE_TAX_NOT_PAID_REMINDER = "REGISTERED_DEVICE_TAX_NOT_PAID_REMINDER";
	String VISA_EXPIRE = "VISA_EXPIRE";
	String CONSIGNMENT_REVENUE = "CONSIGNMENT_REVENUE";
	String CLOSE_GRIEVANCE = "CLOSE_GRIEVANCE";

}
