package com.gl.ceir.config.model.constants;

public enum TransactionState {
	INIT, WAITING_FOR_USER_ACTION, FOR_NOTIFICATION, SEND_TO_BLOCK, BLOCK, ALOW, SEND_TO_COMM, FINISH, WAIT_FOR_DOCUMENT_APPROVAL, DOCUMENT_REJECTED, DOCUMENT_APPROVED;
}
