server:
    port: 9000
    servlet:
        context-path: /substation
    shutdown: graceful
spring:
    datasource:
        hikari:
            maxLifetime: 200000
        password: root@12345
        tomcat:
            initial-size: 15
            max-active: 50
            max-idle: 15
            max-wait: 20000
            min-idle: 8
        url: jdbc:mysql://13.234.49.133:3306/pview?autoReconnect=true&useSSL=false
        username: root
    jackson:
        serialization:
            fail-on-empty-beans: false
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: false
        show-sql: true

