server:
  port: 9004
  servlet:
    context-path: /Modem/
  shutdown: graceful
spring:
  datasource:
    hikari:
      maxLifetime: 200000
    password: root
    tomcat:
      initial-size: 15
      max-active: 50
      max-idle: 15
      max-wait: 20000
      min-idle: 8
    url: 'jdbc:mysql://localhost:3306/messageDB?autoReconnect=true&useSSL=false'
    username: root
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
    show-sql: true
